-- MySQL Script generated by MySQL Workbench
-- Mon Mar 26 16:02:49 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BdSapataria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BdSapataria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BdSapataria` DEFAULT CHARACTER SET utf8 ;
USE `BdSapataria` ;

-- -----------------------------------------------------
-- Table `BdSapataria`.`Pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdSapataria`.`Pessoas` (
  `idPessoas` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(20) NOT NULL,
  `CPF` VARCHAR(20) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  PRIMARY KEY (`idPessoas`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC),
  UNIQUE INDEX `idPessoas_UNIQUE` (`idPessoas` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdSapataria`.`Sapatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdSapataria`.`Sapatos` (
  `idSapatos` INT NOT NULL AUTO_INCREMENT,
  `tamanho` VARCHAR(20) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `qtdEstoque` INT NOT NULL,
  `generoSapato` VARCHAR(10) NOT NULL,
  `tipoSapato` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idSapatos`),
  UNIQUE INDEX `idLoja_UNIQUE` (`idSapatos` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdSapataria`.`Vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdSapataria`.`Vendas` (
  `idVendas` INT NOT NULL AUTO_INCREMENT,
  `Pessoas_idPessoas` INT NOT NULL,
  `dataVenda` VARCHAR(15) NOT NULL,
  `formaPagamento` VARCHAR(40) NOT NULL,
  `total` DOUBLE NOT NULL,
  PRIMARY KEY (`idVendas`),
  UNIQUE INDEX `idVenda_UNIQUE` (`idVendas` ASC),
  INDEX `fk_Vendas_Pessoas1_idx` (`Pessoas_idPessoas` ASC),
  CONSTRAINT `fk_Vendas_Pessoas1`
    FOREIGN KEY (`Pessoas_idPessoas`)
    REFERENCES `BdSapataria`.`Pessoas` (`idPessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdSapataria`.`Vendas_Sapatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdSapataria`.`Vendas_Sapatos` (
  `idVendas` INT NOT NULL,
  `idSapatos` INT NOT NULL,
  `qtdPedidos` INT NOT NULL,
  INDEX `fk_Vendas_Sapatos_Vendas1_idx` (`idVendas` ASC),
  INDEX `fk_Vendas_Sapatos_Sapatos1_idx` (`idSapatos` ASC),
  CONSTRAINT `fk_Vendas_Sapatos_Vendas1`
    FOREIGN KEY (`idVendas`)
    REFERENCES `BdSapataria`.`Vendas` (`idVendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendas_Sapatos_Sapatos1`
    FOREIGN KEY (`idSapatos`)
    REFERENCES `BdSapataria`.`Sapatos` (`idSapatos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
